#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yum
Version  : 3.4.3
Release  : 20
URL      : http://yum.baseurl.org/download/3.4/yum-3.4.3.tar.gz
Source0  : http://yum.baseurl.org/download/3.4/yum-3.4.3.tar.gz
Summary  : RPM installer/updater
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: yum-bin
Requires: yum-python
Requires: yum-data
Requires: yum-locales
Requires: yum-doc
BuildRequires : gettext-bin
BuildRequires : intltool
Patch1: cve-2014-0022.nopatch
Patch2: nolock.patch

%description
Yum is a utility that can check for and automatically download and
install updated RPM packages. Dependencies are obtained and downloaded 
automatically, prompting the user for permission as necessary.

%package bin
Summary: bin components for the yum package.
Group: Binaries
Requires: yum-data

%description bin
bin components for the yum package.


%package data
Summary: data components for the yum package.
Group: Data

%description data
data components for the yum package.


%package doc
Summary: doc components for the yum package.
Group: Documentation

%description doc
doc components for the yum package.


%package locales
Summary: locales components for the yum package.
Group: Default

%description locales
locales components for the yum package.


%package python
Summary: python components for the yum package.
Group: Default

%description python
python components for the yum package.


%prep
%setup -q -n yum-3.4.3
%patch2 -p1

%build
make V=1  %{?_smp_mflags} DESTDIR=%{buildroot}

%install
rm -rf %{buildroot}
%make_install
%find_lang yum
## make_install_append content
rm -rf %{buildroot}%{_sysconfdir}/rc.d
mkdir -p %{buildroot}%{_datadir}/dbus-1/system.d
mv %{buildroot}%{_sysconfdir}/dbus-1/system.d/yum-updatesd.conf %{buildroot}%{_datadir}/dbus-1/system.d
rm -rf %{buildroot}%{_sysconfdir}/dbus-1/
rm -rf %{buildroot}%{_sysconfdir}/cron.daily
rm -rf %{buildroot}%{_sysconfdir}/sysconfig
rm -rf %{buildroot}%{_sysconfdir}/logrotate.d
mkdir -p %{buildroot}%{_datadir}/bash-completion/completions/
mv %{buildroot}%{_sysconfdir}/bash_completion.d/yum.bash %{buildroot}%{_datadir}/bash-completion/completions/yum
rm -rf %{buildroot}%{_sysconfdir}/bash_completion.d
rm -rf %{buildroot}%{_sysconfdir}/yum
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/yum
/usr/bin/yum-updatesd

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/yum
/usr/share/dbus-1/system.d/yum-updatesd.conf
/usr/share/yum-cli/callback.py
/usr/share/yum-cli/callback.pyc
/usr/share/yum-cli/callback.pyo
/usr/share/yum-cli/cli.py
/usr/share/yum-cli/cli.pyc
/usr/share/yum-cli/cli.pyo
/usr/share/yum-cli/output.py
/usr/share/yum-cli/output.pyc
/usr/share/yum-cli/output.pyo
/usr/share/yum-cli/shell.py
/usr/share/yum-cli/shell.pyc
/usr/share/yum-cli/shell.pyo
/usr/share/yum-cli/utils.py
/usr/share/yum-cli/utils.pyc
/usr/share/yum-cli/utils.pyo
/usr/share/yum-cli/yumcommands.py
/usr/share/yum-cli/yumcommands.pyc
/usr/share/yum-cli/yumcommands.pyo
/usr/share/yum-cli/yummain.py
/usr/share/yum-cli/yummain.pyc
/usr/share/yum-cli/yummain.pyo
/usr/share/yum-cli/yumupd.py
/usr/share/yum-cli/yumupd.pyc
/usr/share/yum-cli/yumupd.pyo

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man5/*
%doc /usr/share/man/man8/*

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*

%files locales -f yum.lang 
%defattr(-,root,root,-)

